// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqh2weSXr0kMnL-GKJRQYI9NrmVWxvAw',
    appId: '1:365961918131:web:ba438eea253276b1f662c6',
    messagingSenderId: '365961918131',
    projectId: 'presence-16646',
    authDomain: 'presence-16646.firebaseapp.com',
    storageBucket: 'presence-16646.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI7W996LvEwZ3i5qjZfA57HeSroRRddIU',
    appId: '1:365961918131:android:48865269fa0f9c8df662c6',
    messagingSenderId: '365961918131',
    projectId: 'presence-16646',
    storageBucket: 'presence-16646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-C-8ctdfhTBzGb-uR9AC01C_SX_B7jr0',
    appId: '1:365961918131:ios:b5db96a15efcb1f9f662c6',
    messagingSenderId: '365961918131',
    projectId: 'presence-16646',
    storageBucket: 'presence-16646.appspot.com',
    iosClientId: '365961918131-0l3qe0uh591c8bm86caqludnqt84qbbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-C-8ctdfhTBzGb-uR9AC01C_SX_B7jr0',
    appId: '1:365961918131:ios:b5db96a15efcb1f9f662c6',
    messagingSenderId: '365961918131',
    projectId: 'presence-16646',
    storageBucket: 'presence-16646.appspot.com',
    iosClientId: '365961918131-0l3qe0uh591c8bm86caqludnqt84qbbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
